name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Build the Docker backend image
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}
          REACT_APP_ALLOWED_HOST: ${{ secrets.REACT_APP_ALLOWED_HOST }}
        run: |
          sudo docker-compose -p fullstack up --build -d

#      - name: Running django server
#        run: |
#          cd backend
#          sudo docker run -d -p 8000:8000 --name backend-container backend:latest
#          sleep 20

#      - name: Api call server
#        run: |
#          curl 127.0.0.1:8000/demoapp/allBooks

#      - name: Build the Docker frontend image
#        run: |
#          cd frontend
#          sudo docker build -t frontend .

#      - name: Running Frontend
#        run: |
#          cd frontend
#          sudo docker run -d -p 3000:3000 --name frontend-container frontend:latest
#          sleep 20

#      - name: Clean up docker backend container and image
#        run: |
#          cd backend
#          docker stop backend-container
#          docker rm backend-container
#          docker rmi backend
#
#      - name: Clean up docker frontend container and image
#        run: |
#          cd frontend
#          docker stop frontend-container
#          docker rm frontend-container
#          docker rmi frontend