name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker backend image
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOST: ${{ secrets.ALLOWED_HOST }}
        run: |
          cd backend
          docker build --build-arg POSTGRES_USER=$POSTGRES_USER --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_HOST=$POSTGRES_HOST --build-arg SECRET_KEY=$SECRET_KEY --build-arg DEBUG=$DEBUG --build-arg ALLOWED_HOST=$ALLOWED_HOST -t backend .

      - name: Running django server
        run: |
          cd backend
          docker run -d -p 8000:8000 --name backend-container backend:latest
          sleep 20

#      - name: Api call server
#        run: |
#          curl 127.0.0.1:8000/demoapp/allBooks

      - name: Build the Docker frontend image
        run: |
          cd frontend
          docker build -t frontend .

      - name: Running django server
        run: |
          cd frontend
          docker run -d -p 3000:3000 --name frontend-container frontend:latest
          sleep 20

      - name: Clean up docker backend container and image
        run: |
          cd backend
          docker stop backend-container
          docker rm backend-container
          docker rmi backend

      - name: Clean up docker frontend container and image
        run: |
          cd frontend
          docker stop frontend-container
          docker rm frontend-container
          docker rmi frontend